import { useEffect, useState } from 'react';
import { ExternalLink, Github, Laptop, LogIn, Mail, ShieldCheck, Trash2, UserRound } from 'lucide-react';
import { open } from '@tauri-apps/plugin-shell';
import { auth, type AccountDevice } from './lib/auth';
import type { AccountUser } from './lib/api';

type Mode='login'|'register'|'forgot';

export function Account({user,onUserChange}:{user:AccountUser|null;onUserChange:(user:AccountUser|null)=>void}){
 const[mode,setMode]=useState<Mode>('login'),[email,setEmail]=useState(''),[password,setPassword]=useState(''),[name,setName]=useState(''),[message,setMessage]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false),[devices,setDevices]=useState<AccountDevice[]>([]);
 useEffect(()=>{if(user)void auth.devices().then(setDevices).catch(e=>setError(String(e)))},[user]);
 const run=async()=>{setBusy(true);setError('');setMessage('');try{if(mode==='forgot'){await auth.forgotPassword(email);setMessage('If an account exists for that email, reset instructions have been sent.')}else{const next=mode==='login'?await auth.signIn(email,password):await auth.signUp(name,email,password);onUserChange(next)}}catch(e){setError(String(e))}finally{setBusy(false)}};
 const oauth=async(provider:'google'|'github')=>{if(!auth.configured){setError('Forge account services are not configured in this build.');return}setBusy(true);setError('');try{const next=await auth.oauth(provider,started=>{void open(started.verification_uri);setMessage(`Complete sign-in in your browser. Verification code: ${started.user_code}`)});onUserChange(next)}catch(e){setError(String(e))}finally{setBusy(false)}};
 if(user)return <div className="account-layout"><section className="panel account-card"><div className="account-avatar"><UserRound/></div><div><span className="eyebrow">Forge account</span><h2>{user.display_name||user.email}</h2><p>{user.email}</p><span className={`status-pill ${user.email_verified?'verified':''}`}>{user.email_verified?<><ShieldCheck/>Verified</>:<>Email verification required</>}</span></div>{!user.email_verified&&<button className="secondary" onClick={()=>void auth.resendVerification().then(()=>setMessage('Verification email sent.')).catch(e=>setError(String(e)))}><Mail/>Resend email</button>}</section><section className="panel"><div className="section-heading"><div><h2>Connected devices</h2><p>Revoke sessions you no longer recognize.</p></div><Laptop/></div>{devices.map(d=><div className="row" key={d.id}><span className="provider"><Laptop/></span><div><strong>{d.name}{d.current?' · This device':''}</strong><small>{d.platform} · Last active {new Date(d.last_seen_at).toLocaleString()}</small></div>{!d.current&&<button className="secondary" onClick={()=>void auth.revokeDevice(d.id).then(()=>setDevices(x=>x.filter(v=>v.id!==d.id)))}>Revoke</button>}</div>)}</section><section className="panel danger-zone"><h2>Account security</h2><p>Signing out never deletes local chats, usage, settings, or provider credentials.</p><div className="account-actions"><button className="secondary" onClick={()=>void auth.signOut().then(()=>onUserChange(null))}>Sign out</button><button className="secondary" onClick={()=>void auth.signOutAll().then(()=>onUserChange(null))}>Sign out all devices</button><button className="danger-button" onClick={()=>{if(confirm('Permanently delete your Forge account? Local data on this device will remain.'))void auth.deleteAccount().then(()=>onUserChange(null))}}><Trash2/>Delete account</button></div></section>{message&&<div className="success">{message}</div>}{error&&<div className="error">{error}</div>}</div>;
 return <div className="auth-layout"><section className="auth-copy"><span className="eyebrow">Optional Forge account</span><h2>Local Mode works without signing in.</h2><p>Create an account for device management and future encrypted sync. Your chats, usage history, settings, and provider API keys stay on this device.</p><div className="privacy-note"><ShieldCheck/><div><strong>Provider credentials remain local</strong><small>Signing in never uploads keys from macOS Keychain or Windows Credential Manager.</small></div></div></section><section className="panel auth-card"><h2>{mode==='login'?'Sign in':mode==='register'?'Create account':'Reset password'}</h2><p>{auth.configured?'Use your Forge account credentials.':'Account services are not configured in this build; continue using Local Mode.'}</p>{mode!=='forgot'&&<div className="oauth-buttons"><button className="secondary" disabled={!auth.configured} onClick={()=>void oauth('google')}><ExternalLink/>Continue with Google</button><button className="secondary" disabled={!auth.configured} onClick={()=>void oauth('github')}><Github/>Continue with GitHub</button></div>}{mode==='register'&&<label>Display name<input autoComplete="name" value={name} onChange={e=>setName(e.target.value)}/></label>}<label>Email<input type="email" autoComplete="email" value={email} onChange={e=>setEmail(e.target.value)}/></label>{mode!=='forgot'&&<label>Password<input type="password" autoComplete={mode==='login'?'current-password':'new-password'} value={password} onChange={e=>setPassword(e.target.value)}/><small>{mode==='register'?'Use at least 12 characters.':''}</small></label>}{error&&<div className="error">{error}</div>}{message&&<div className="success">{message}</div>}<button disabled={busy||!auth.configured||!email||(mode!=='forgot'&&!password)||(mode==='register'&&(!name||password.length<12))} onClick={()=>void run()}><LogIn/>{busy?'Please wait…':mode==='login'?'Sign in':mode==='register'?'Create account':'Send reset link'}</button><div className="auth-links">{mode!=='login'&&<button onClick={()=>setMode('login')}>Back to sign in</button>}{mode==='login'&&<><button onClick={()=>setMode('forgot')}>Forgot password?</button><button onClick={()=>setMode('register')}>Create account</button></>}</div></section></div>;
}
