import { useEffect, useState } from 'react';
import { Activity, Cloud, Gauge, Plus, Send, Server, Settings } from 'lucide-react';
import { api, type Connection, type Metrics, type UsageSummary } from './lib/api';

type Tab='dashboard'|'connections'|'playground'|'usage'|'settings';
const labels:Record<Connection['kind'],string>={local_ollama:'Local Ollama',remote_ollama:'Remote Ollama / Linux server',openai:'OpenAI API',anthropic:'Anthropic API',gemini:'Google Gemini API',openai_compatible:'OpenAI-compatible API'};
const emptyUsage:UsageSummary={total_requests:0,input_tokens:0,output_tokens:0,total_tokens:0,estimated_cost:0,by_connection:[],recent:[]};
const emptyMetrics:Metrics={cpu_usage:0,total_memory:0,used_memory:0,available_memory:0,platform:'',architecture:'',cpu_brand:'',logical_cores:0,gpu_name:''};
export default function App(){const[tab,setTab]=useState<Tab>('dashboard');const[metrics,setMetrics]=useState(emptyMetrics);const[connections,setConnections]=useState<Connection[]>([]);const[usage,setUsage]=useState(emptyUsage);const[error,setError]=useState('');const refresh=async()=>{try{const[m,c,u]=await Promise.all([api.metrics(),api.connections(),api.usage()]);setMetrics(m);setConnections(c);setUsage(u)}catch(e){setError(String(e))}};useEffect(()=>{refresh();const t=setInterval(refresh,4000);return()=>clearInterval(t)},[]);return <div className="shell"><aside><div className="brand"><b>F</b><div><strong>Forge AI</strong><small>Version 1.0.0</small></div></div><nav>{(['dashboard','connections','playground','usage','settings'] as Tab[]).map(x=><button className={tab===x?'active':''} onClick={()=>setTab(x)} key={x}>{icons[x]}{x}</button>)}</nav><div className="device"><small>This device</small><strong>{metrics.cpu_brand||'Detecting hardware…'}</strong><span>{metrics.logical_cores} cores · {(metrics.total_memory/1024**3).toFixed(1)} GB RAM<br/>{metrics.gpu_name}</span></div></aside><main><header><small>FORGE AI 1.0.0</small><h1>{titles[tab]}</h1><p>One desktop control center for local, remote, and cloud AI.</p></header>{error&&<div className="error">{error}</div>}{tab==='dashboard'&&<Dashboard metrics={metrics} connections={connections} usage={usage}/>} {tab==='connections'&&<Connections items={connections} refresh={refresh}/>} {tab==='playground'&&<Playground items={connections} refresh={refresh}/>} {tab==='usage'&&<Usage usage={usage}/>} {tab==='settings'&&<section className="panel"><h2>Settings</h2><p>Remote Linux servers are supported through Ollama or OpenAI-compatible connection URLs. Secure OS credential storage is the next hardening task.</p></section>}</main></div>}
const icons={dashboard:<Gauge/>,connections:<Cloud/>,playground:<Send/>,usage:<Activity/>,settings:<Settings/>};const titles={dashboard:'AI control center',connections:'Provider connections',playground:'Unified playground',usage:'Tokens and cost',settings:'Application settings'};
function Dashboard({metrics,connections,usage}:{metrics:Metrics;connections:Connection[];usage:UsageSummary}){return <><div className="cards"><Card label="Connections" value={String(connections.length)}/><Card label="Requests" value={String(usage.total_requests)}/><Card label="Tokens" value={usage.total_tokens.toLocaleString()}/><Card label="CPU" value={`${metrics.cpu_usage.toFixed(0)}%`}/></div><section className="panel"><h2>Execution targets</h2>{connections.length?connections.map(c=><div className="row" key={c.id}><span className="provider">{c.kind.includes('ollama')?<Server/>:<Cloud/>}</span><div><strong>{c.name}</strong><small>{labels[c.kind]} · {c.default_model||'Select model per request'}</small></div></div>):<p>No connections yet. Add a local runtime, remote Linux server, or cloud API.</p>}</section></>}
function Connections({items,refresh}:{items:Connection[];refresh:()=>Promise<void>}){const[form,setForm]=useState<Connection|null>(null);const save=async()=>{if(form){await api.saveConnection(form);setForm(null);await refresh()}};return <><div className="toolbar"><div><h2>Connections</h2><p>Cloud providers require API access; consumer subscriptions are not reusable API credentials.</p></div><button onClick={()=>setForm({id:crypto.randomUUID(),name:'',kind:'remote_ollama',base_url:'http://',api_key:'',default_model:'',enabled:true,input_cost_per_million:0,output_cost_per_million:0})}><Plus/>Add</button></div><section className="panel">{items.map(c=><div className="row" key={c.id}><span className="provider"><Cloud/></span><div><strong>{c.name}</strong><small>{labels[c.kind]} · {c.base_url}</small></div><button onClick={()=>setForm(c)}>Edit</button></div>)}</section>{form&&<div className="modal"><div className="dialog"><h2>Connection</h2><input placeholder="Name" value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/><select value={form.kind} onChange={e=>setForm({...form,kind:e.target.value as Connection['kind']})}>{Object.entries(labels).map(([k,v])=><option value={k} key={k}>{v}</option>)}</select><input placeholder="Base URL" value={form.base_url} onChange={e=>setForm({...form,base_url:e.target.value})}/><input placeholder="API key" type="password" value={form.api_key} onChange={e=>setForm({...form,api_key:e.target.value})}/><input placeholder="Default model" value={form.default_model} onChange={e=>setForm({...form,default_model:e.target.value})}/><div><button onClick={()=>setForm(null)}>Cancel</button><button onClick={save}>Save</button></div></div></div>}</>}
function Playground({items,refresh}:{items:Connection[];refresh:()=>Promise<void>}){const[id,setId]=useState('');const[model,setModel]=useState('');const[prompt,setPrompt]=useState('Explain how to safely refactor a TypeScript service.');const[result,setResult]=useState('');const send=async()=>{const r=await api.chat(id,model,prompt);setResult(r.response);await refresh()};return <section className="panel"><div className="two"><select value={id} onChange={e=>{setId(e.target.value);setModel(items.find(x=>x.id===e.target.value)?.default_model||'')}}><option value="">Select provider</option>{items.map(c=><option value={c.id} key={c.id}>{c.name}</option>)}</select><input value={model} onChange={e=>setModel(e.target.value)} placeholder="Model ID"/></div><textarea value={prompt} onChange={e=>setPrompt(e.target.value)}/><button onClick={send} disabled={!id||!model}><Send/>Send</button>{result&&<pre>{result}</pre>}</section>}
function Usage({usage}:{usage:UsageSummary}){return <div className="cards"><Card label="Requests" value={String(usage.total_requests)}/><Card label="Input tokens" value={usage.input_tokens.toLocaleString()}/><Card label="Output tokens" value={usage.output_tokens.toLocaleString()}/><Card label="Estimated cost" value={`$${usage.estimated_cost.toFixed(4)}`}/></div>}
function Card({label,value}:{label:string;value:string}){return <div className="card"><small>{label}</small><strong>{value}</strong></div>}
